### ISSUE TITLE
C++11 build errors

### ISSUE THREAD

**Issue by fedorov** [QIICR/dcmqi#235]
As reported by @nolden: "Currently it doesn't build with recent compilers, e.g. gcc 6.3 on Fedora"

**Comment by fedorov** [comment]
I've set up a docker with compiler in question, and am in the process of building dcmqi. I will report later today on the result.

**Comment by nolden** [comment]
Just checked: most recent 0.x.y jsoncpp unfortunately shows the same errors.

**Comment by nolden** [comment]
Another info: most recent jsoncpp also builds with `-std=c++03` , so maybe you could pass this from the Slicer superbuild to dcmqi @jcfr what do you think?

**Comment by fedorov** [comment]
@nolden I confirm I can also reproduce the compile errors with the docker I configured.

Let me try the suggestion you made, and test if it passess CircleCI.

**Comment by fedorov** [comment]
> most recent jsoncpp also builds with `-std=c++03`

But wait, this is not a universal flag, is it? We should make sure it builds on all 3 operating systems, including Visual Studio version that is used by Slicer dashboard. We don't even have a way to test that specific Visual Studio outside the dashboard.

**Comment by nolden** [comment]
> But wait, this is not a universal flag, is it? 

No, but it's a strong indication that there are no mandatory C++11 features in jsoncpp. Instead of setting the flag directly you could also use CMake's cross-platform features for selecting the C++ standard version, again rather on the superbuild level above dcmqi

**Comment by fedorov** [comment]
@nolden yes, I agree with you. I am just not familiar with how to select standard C++ in VC, and whether it is version-specific. I will look into that.

**Comment by fedorov** [comment]
reported in jsoncpp project: https://github.com/open-source-parsers/jsoncpp/issues/600

**Comment by nolden** [comment]
Thanks for reporting there. Seems to me a switch to a newer version would be the easiest to maintain if that still builds on older compilers with C++ 0x. You can use CMake to set this without knowing about all the different flags: https://cmake.org/cmake/help/v3.1/variable/CMAKE_CXX_STANDARD.html#variable:CMAKE_CXX_STANDARD

**Comment by fedorov** [comment]
@nolden thank you for the hints!

I am experimenting with this cmake feature in this branch: https://github.com/fedorov/dcmqi/tree/add-cxx-standard-property using this docker: https://github.com/fedorov/dcmqi-docker-tests/blob/master/Dockerfile.gcc63.

At the moment, stumbled how to propagate CMAKE_CXX_STANDARD to the dcmqi target. Independently of the jsoncpp update/changes, we need to set std++98 for all targets, since std++14 is default for gcc 6: https://gcc.gnu.org/gcc-6/changes.html.

**Comment by fedorov** [comment]
@nolden I could not figure out how to set CMAKE_CXX_STANDARD variable - the flags are not set for the compiler.

When I manually set `-std=c++98` for ITK, I get compile error with gcc 6.3. Will next test if I can compile the latest ITK.

```
[ 85%] Building CXX object Modules/Filtering/Path/src/CMakeFiles/ITKPath.dir/itkOrthogonallyCorrected2DParametricPath.cxx.o
In file included from /home/work/dcmqi-build/ITK/Modules/IO/ImageBase/include/itkImageFileWriter.hxx:34:0,
                 from /home/work/dcmqi-build/ITK/Modules/IO/ImageBase/include/itkImageFileWriter.h:227,
                 from /home/work/dcmqi-build/ITK/Modules/IO/ImageBase/include/itkImageSeriesWriter.h:23,
                 from /home/work/dcmqi-build/ITK/Modules/IO/ImageBase/src/itkImageSeriesWriter.cxx:18:
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:34:38: error: 'tr1' in namespace 'std' does not name a type
 #  define ITK_STD_TR1_NAMESPACE std::tr1
                                      ^
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:57:13: note: in expansion of macro 'ITK_STD_TR1_NAMESPACE'
     typedef ITK_STD_TR1_NAMESPACE::true_type  TrueType;
             ^~~~~~~~~~~~~~~~~~~~~
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:34:38: error: 'tr1' in namespace 'std' does not name a type
 #  define ITK_STD_TR1_NAMESPACE std::tr1
                                      ^
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:58:13: note: in expansion of macro 'ITK_STD_TR1_NAMESPACE'
     typedef ITK_STD_TR1_NAMESPACE::false_type FalseType;
             ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by fedorov** [comment]
Unable to compile plain ITKv4 (the same hash as is used by Slicer https://github.com/Slicer/Slicer/blob/master/SuperBuild/External_ITKv4.cmake#L45) with gcc 6.3 and with `-std=c++98`.

@thewtex do you know if this is expected to work?

```
[ 34%] Built target ITKCommonHeaderTest9
[ 34%] Building CXX object Modules/Core/Common/CMakeFiles/ITKCommonHeaderTest2.dir/test/ITKCommonHeaderTest2.cxx.o
In file included from /usr/include/c++/6.3.1/type_traits:35:0,
                 from /home/work/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:24,
                 from /home/work/ITK/Modules/Core/Common/include/itkImageDuplicator.hxx:22,
                 from /home/work/ITKv4-build/Modules/Core/Common/test/ITKCommonHeaderTest2.cxx:27:
/usr/include/c++/6.3.1/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^~~~~
In file included from /home/work/ITK/Modules/Core/Common/include/itkImageDuplicator.hxx:22:0,
                 from /home/work/ITKv4-build/Modules/Core/Common/test/ITKCommonHeaderTest2.cxx:27:
/home/work/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:34:38: error: 'tr1' in namespace 'std' does not name a type
 #  define ITK_STD_TR1_NAMESPACE std::tr1
                                      ^
```

**Comment by thewtex** [comment]
@fedorov We do not have a dashboard build for that specific configuration, but I expect that it would work.

Make sure that `-std=c++98` is passed during the initial CMake configuration, because the settings detected are used in further builds.  From a clean build tree, something like

```
CXXFLAGS=-std=c++98 cmake ~/src/ITK
```

or

```
cmake -DCMAKE_CXX_FLAGS=-std=c++98 ~/src/ITK
```

**Comment by fedorov** [comment]
@thewtex thank you, I confirm I can compile ITK with gcc 6.3 using this approach.

Back to dcmqi issue, still have troubles related to C++11, even when setting `CXXFLAGS` variable before doing anything else, don't know what is causing them. Some errors come from ITK, but I can't blame ITK alone for this!

```
[  2%] Building CXX object libsrc/CMakeFiles/dcmqi.dir/ConverterBase.cpp.o
In file included from /usr/include/c++/6.3.1/cstdint:35:0,
                 from /home/work/dcmqi-build/DCMTK/ofstd/include/dcmtk/ofstd/ofstdinc.h:279,
                 from /home/work/dcmqi-build/DCMTK/ofstd/include/dcmtk/ofstd/oftypes.h:74,
                 from /home/work/dcmqi-build/DCMTK/ofstd/include/dcmtk/ofstd/ofvector.h:47,
                 from /home/work/dcmqi-build/DCMTK/oflog/include/dcmtk/oflog/loglevel.h:35,
                 from /home/work/dcmqi/include/dcmqi/ConverterBase.h:14,
                 from /home/work/dcmqi/libsrc/ConverterBase.cpp:3:
/usr/include/c++/6.3.1/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^~~~~
In file included from /home/work/dcmqi-build/ITK/Modules/IO/ImageBase/include/itkImageFileWriter.hxx:34:0,
                 from /home/work/dcmqi-build/ITK/Modules/IO/ImageBase/include/itkImageFileWriter.h:227,
                 from /home/work/dcmqi/include/dcmqi/ConverterBase.h:27,
                 from /home/work/dcmqi/libsrc/ConverterBase.cpp:3:
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:57:36: error: 'true_type' in namespace 'std' does not name a type
     typedef ITK_STD_TR1_NAMESPACE::true_type  TrueType;
                                    ^~~~~~~~~
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:58:36: error: 'false_type' in namespace 'std' does not name a type
     typedef ITK_STD_TR1_NAMESPACE::false_type FalseType;
                                    ^~~~~~~~~~
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h: In static member function 'static void itk::ImageAlgorithm::Copy(const itk::Image<TPixel1, VImageDimension>*, itk::Image<TPixel2, VImageDimension>*, const typename itk::Image<TPixel1, VImageDimension>::RegionType&, const typename itk::Image<TPixel2, VImageDimension>::RegionType&)':
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:32:33: error: 'is_convertible' is not a member of 'std'
 #  define ITK_STD_TR1_NAMESPACE std
                                 ^
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:104:38: note: in expansion of macro 'ITK_STD_TR1_NAMESPACE'
                                    , ITK_STD_TR1_NAMESPACE::is_convertible<typename _ImageType1::PixelType,
                                      ^~~~~~~~~~~~~~~~~~~~~
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:104:107: error: expected '(' before ',' token
                                    , ITK_STD_TR1_NAMESPACE::is_convertible<typename _ImageType1::PixelType,
                                                                                                           ^
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:105:67: error: expected '(' before '>' token
                                    typename _ImageType2::PixelType>()
                                                                   ^
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:105:69: error: expected primary-expression before ')' token
                                    typename _ImageType2::PixelType>()
                                                                     ^
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h: In static member function 'static void itk::ImageAlgorithm::Copy(const itk::VectorImage<TPixel1, VImageDimension>*, itk::VectorImage<TPixel2, VImageDimension>*, const typename itk::VectorImage<TPixel1, VImageDimension>::RegionType&, const typename itk::VectorImage<TPixel2, VImageDimension>::RegionType&)':
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:32:33: error: 'is_convertible' is not a member of 'std'
 #  define ITK_STD_TR1_NAMESPACE std
                                 ^
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:125:38: note: in expansion of macro 'ITK_STD_TR1_NAMESPACE'
                                    , ITK_STD_TR1_NAMESPACE::is_convertible<typename _ImageType1::PixelType,
                                      ^~~~~~~~~~~~~~~~~~~~~
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:125:107: error: expected '(' before ',' token
                                    , ITK_STD_TR1_NAMESPACE::is_convertible<typename _ImageType1::PixelType,
                                                                                                           ^
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:126:67: error: expected '(' before '>' token
                                    typename _ImageType2::PixelType>()
                                                                   ^
/home/work/dcmqi-build/ITK/Modules/Core/Common/include/itkImageAlgorithm.h:126:69: error: expected primary-expression before ')' token
                                    typename _ImageType2::PixelType>()
                                                                     ^
libsrc/CMakeFiles/dcmqi.dir/build.make:62: recipe for target 'libsrc/CMakeFiles/dcmqi.dir/ConverterBase.cpp.o' failed
make[2]: *** [libsrc/CMakeFiles/dcmqi.dir/ConverterBase.cpp.o] Error 1
CMakeFiles/Makefile2:981: recipe for target 'libsrc/CMakeFiles/dcmqi.dir/all' failed
make[1]: *** [libsrc/CMakeFiles/dcmqi.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by nolden** [comment]
Oh, this looks like an CMake / ITK problem ([Gitlab](https://gitlab.kitware.com/cmake/cmake/issues?scope=all&utf8=%E2%9C%93&state=opened&search=15361), [Mantis](https://cmake.org/Bug/view.php?id=15361)) we have also encountered in MITK, thought it was fixed but at first glance it looks like the same problem, we worked around it by specifying the flags directly for sub-projects which are affected (like ITK). @thewtex : do you know anything about this?

The (non-working) solution using CXX_STANDARD looks like this: https://github.com/nolden/dcmqi/commit/961cc82aa8784c7be12728b03925bf33d5b58f3b

@fedorov : does Slicer superbuild work with gcc 6.3 ?

If we can sort this issue out, would you agree to update jsoncpp to a more recent version?

**Comment by nolden** [comment]
@fedorov : actually I should rephrase my last question. Updating jsoncpp should fix the problems with gcc 6.3 and it should still build with C++98 , independent of the ITK/CMake problems. But what was the original error the CircleCI compilers had with the newer jsoncpp? I think this was the rationale behind downgrading it.

**Comment by fedorov** [comment]
> @fedorov : does Slicer superbuild work with gcc 6.3 ?

I don't know, and I don't have a good way to test this. I was doing dcmqi gcc 6.3 tests using [this Dockerfile](https://github.com/fedorov/dcmqi-docker-tests/blob/master/Dockerfile.gcc63). I guess I could set one up for Slicer too.

> If we can sort this issue out, would you agree to update jsoncpp to a more recent version?

Let's review the facts: 

1) jsoncpp [1.y.z is built with C++11](https://github.com/open-source-parsers/jsoncpp) according to jsoncpp README

2) Slicer is not expected to build with C++11

3) build on Fedora is failing due to a combination of reasons: gcc 6.3 by default is using C++11 and flags that are expected to set C++98 do not propagate properly.

So I think the proper solution to the problem you experience is not update to 1.x.y, but fix the issue with incorrect propagation of flags so that C++98 is used with gcc 6.3. Do you agree?

> Updating jsoncpp should fix the problems with gcc 6.3 and it should still build with C++98

Well, that is the hypothesis to be tested on all 3 platforms that are used to build Slicer ... and even if it works, how can we say it will stay this way, since jsoncpp explicitly says C++11 is needed for 1.x.y?

> But what was the original error the CircleCI compilers had with the newer jsoncpp? 

It was indeed related to C++11: https://circleci.com/gh/QIICR/dcmqi/92

```
/home/ubuntu/dcmqi/jsoncpp/json/json.h:1752:31: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   CharReader* newCharReader() const JSONCPP_OVERRIDE;
                               ^
/home/ubuntu/dcmqi/jsoncpp/json/json.h:1947:24: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   ~StreamWriterBuilder() JSONCPP_OVERRIDE;
                        ^
/home/ubuntu/dcmqi/jsoncpp/json/json.h:1952:35: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   StreamWriter* newStreamWriter() const JSONCPP_OVERRIDE;
                                   ^
/home/ubuntu/dcmqi/jsoncpp/json/json.h:1993:15: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   ~FastWriter() JSONCPP_OVERRIDE {}
               ^
/home/ubuntu/dcmqi/jsoncpp/json/json.h:2007:41: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   JSONCPP_STRING write(const Value& root) JSONCPP_OVERRIDE;
                                         ^
/home/ubuntu/dcmqi/jsoncpp/json/json.h:2045:17: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   ~StyledWriter() JSONCPP_OVERRIDE {}
                 ^
/home/ubuntu/dcmqi/jsoncpp/json/json.h:2052:41: warning: override controls (override/final) only available with -std=c++11 or -std=gnu++11
   JSONCPP_STRING write(const Value& root) JSONCPP_OVERRIDE;
```

With all that said, we could instead just switch to rapidjson:
* we know it works with Slicer: https://github.com/Slicer/Slicer/pull/646
* it is magnitudes faster than jsoncpp: https://github.com/miloyip/nativejson-benchmark
* there's already an issue for replacing jsoncpp with rapidjson, this issue just adds more motivation: https://github.com/QIICR/dcmqi/issues/161

This would probably be my preferred solution, because alternative is debugging cmake/ITK/etc, which is close to intractable for me, and gives no long term benefit. Moving to rapidjson just seems to make sense. What do you think?

**Comment by thewtex** [comment]
> Oh, this looks like an CMake / ITK problem (Gitlab, Mantis) we have also encountered in MITK, thought it > was fixed but at first glance it looks like the same problem, we worked around it by specifying the flags  directly for sub-projects which are affected (like ITK). @thewtex : do you know anything about this?

>The (non-working) solution using CXX_STANDARD looks like this: nolden@961cc82

I know there have been many fixes in recent CMake for propagating this type of information -- it is worth trying the build with the latest release of CMake.

**Comment by nolden** [comment]
> @fedorov : does Slicer superbuild work with gcc 6.3 ?
> 
> I don't know, and I don't have a good way to test this. I was doing dcmqi gcc 6.3 tests using this Dockerfile. I guess I could set one up for Slicer too.

I was just asking, since if Slicer aims at being compatible with gcc 6.3, it would also need a solution to properly enforce older C++ standard in all projects.

> 
> Let's review the facts:
> 
>     jsoncpp 1.y.z is built with C++11 according to jsoncpp README
> 

Yes, but it also builds with C++98, see above

>     Slicer is not expected to build with C++11
> 

I think there is a difference between using C++11 or being buildable with C++11 features enabled. In general the language is backwards compatible. For the MSVC compilers there is even no option to set C++98, you have to switch back to an older cl.exe to use C++98 in say MSVC 2015. 

>     build on Fedora is failing due to a combination of reasons: gcc 6.3 by default is using C++11 and flags that are expected to set C++98 do not propagate properly.
> 
> So I think the proper solution to the problem you experience is not update to 1.x.y, but fix the issue with incorrect propagation of flags so that C++98 is used with gcc 6.3. Do you agree?
> 
Not fully, sorry. Propagating the flags would not solve the issue, since I want to compile MITK with C++11 (actually C++14) flags and the general recommendation is to keep this setting consistent through your whole build. 
>
>     Updating jsoncpp should fix the problems with gcc 6.3 and it should still build with C++98
> 
> Well, that is the hypothesis to be tested on all 3 platforms that are used to build Slicer ... and even if it works, how can we say it will stay this way, since jsoncpp explicitly says C++11 is needed for 1.x.y?
> 
We could ensure this by just not updating 1.x.y anymore, like it's not updated at the moment. For the Slicer platforms I cannot estimate how difficult this will be to test. 

>     But what was the original error the CircleCI compilers had with the newer jsoncpp?
> 
> It was indeed related to C++11: https://circleci.com/gh/QIICR/dcmqi/92
> 
Ok, this was an older version of 1.x.y . In the current one that worked for me they improved the version detection a lot, JSON_CPP_OVERRIDE seems to be intended to distinguish this but it had a bug ...

> 
> With all that said, we could instead just switch to rapidjson:
> 
>     we know it works with Slicer: Slicer/Slicer#646
>     it is magnitudes faster than jsoncpp: https://github.com/miloyip/nativejson-benchmark
>     there's already an issue for replacing jsoncpp with rapidjson, this issue just adds more motivation: #161
> 
> This would probably be my preferred solution, because alternative is debugging cmake/ITK/etc, which is close to intractable for me, and gives no long term benefit. Moving to rapidjson just seems to make sense. What do you think?

Looks very nice and active for me. Any idea of a timeframe?

Would it be ok if I create a pull request for dcmqi which allows for using jsoncpp 1.x.y as an option? Could be easier than patching the whole file back on the MITK side and it would also allow others to make use of it if necessary.

**Comment by fedorov** [comment]
@nolden now that you clarify that you need it to build with C++11 (14!) support, your argument makes sense to me.

> Looks very nice and active for me. Any idea of a timeframe?

It is not the first priority. I need to finish refactoring of the code before taking on any new features.

> Ok, this was an older version of 1.x.y . In the current one that worked for me they improved the version detection a lot

Would you mind making a PR with the update? Let's see if it works on CIs, and then on Slicer dashboard, and if all goes well, we might just upgrade it, and later switch to rapidjson.

> Would it be ok if I create a pull request for dcmqi which allows for using jsoncpp 1.x.y as an option? 

If this will be set at compile time, and won't break 0.x.y option - definitely, your contribution is welcome!

**Comment by nolden** [comment]
> Would you mind making a PR with the update? Let's see if it works on CIs, and then on Slicer dashboard, and if all goes well, we might just upgrade it, and later switch to rapidjson.
> 
Ok, just to make sure I understand you correctly: could you test this for Slicer? Or should I go for the second option, making it optional?

**Comment by nolden** [comment]
> I know there have been many fixes in recent CMake for propagating this type of information -- it is worth trying the build with the latest release of CMake.

@thewtex  Thanks for the hint! I just tested this with most recent CMake, unfortunately it shows the same errors. I think I have to create a minimal non-working example for the bug report.

**Comment by fedorov** [comment]
> Ok, just to make sure I understand you correctly: could you test this for Slicer? Or should I go for the second option, making it optional?

@nolden I don't have the capacity to test it for Slicer. I don't even have a Slicer developer environment set up for Windows (it requires an old version of Visual Studio, which I don't want to install on the only Windows box that I have, since it might mess up my existing recent Visual Studio installation). 

What I suggested to do is 1) make a PR with the update - this will test dcmqi on all platforms; 2) if tests pass, take a risk and integrate, and take a look at Slicer dashboards if this caused any issues.

Making it optional would be preferred. If we see problems on Slicer dashboard, it will be easy to quickly revert to using 0.x.y for Slicer and still keep 1.x.y for MITK, instead of reverting commit.

**Comment by jcfr** [comment]
Closing. Slicer, DCMTK and DCMQI can now all be built with C++11 enabled
